/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#554300',
        'surface-container-low': '#1c1b1b',
        'outline': '#99907c',
        'secondary-fixed-dim': '#d6c68a',
        'surface-bright': '#3a3939',
        'surface-container-highest': '#353534',
        'secondary': '#d6c68a',
        'on-surface-variant': '#d0c5af',
        'primary': '#f2ca50',
        'primary-fixed': '#ffe088',
        'on-background': '#e5e2e1',
        'on-surface': '#e5e2e1',
        'outline-variant': '#4d4635',
        'background': '#131313',
        'secondary-container': '#514616',
        'surface-dim': '#131313',
        'primary-fixed-dim': '#e9c349',
        'surface-container': '#201f1f',
        'on-secondary-container': '#c4b57a',
        'surface-container-lowest': '#0e0e0e',
        'surface': '#131313',
        'surface-variant': '#353534',
        'primary-container': '#d4af37',
        'surface-container-high': '#2a2a2a',
        'secondary-fixed': '#f3e2a3',
        'tertiary': '#d0cdcd',
        'on-primary': '#3c2f00',
      },
      borderRadius: {
        // Keep `full` at Tailwind's default (9999px) so pills + circles stay round.
        lg: '0.25rem',
        xl: '0.5rem',
      },
      spacing: {
        'card-padding': '32px',
        'section-gap-mobile': '64px',
        'grid-gutter': '24px',
        'section-gap': '120px',
      },
      maxWidth: {
        'container-max-width': '1200px',
      },
      fontFamily: {
        'body-md': ['DM Sans', 'sans-serif'],
        'display-lg': ['Bebas Neue', 'sans-serif'],
        'headline-md': ['Bebas Neue', 'sans-serif'],
        'body-lg': ['DM Sans', 'sans-serif'],
        'title-sm': ['DM Sans', 'sans-serif'],
        'label-bold': ['DM Sans', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': ['80px', { lineHeight: '80px', letterSpacing: '0.02em', fontWeight: '400' }],
        'headline-md': ['40px', { lineHeight: '44px', letterSpacing: '0.05em', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'title-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.1em', fontWeight: '700' }],
        'label-bold': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
